@baseUrl = http://localhost:8080/api/produtos

###
post {{baseUrl}}
Content-Type: application/json

{
    "descricao": "Mouse Gamer",
    "preco": 150
}

###
get {{baseUrl}}/1

###
put {{baseUrl}}/1
Content-Type: application/json

{
    "descricao": "Mouse Gamer II",
    "preco": 200
}

###
get {{baseUrl}}?descricao=Gam

###
delete {{baseUrl}}/1