@baseUrl = http://localhost:8080/api/clientes
@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJsdWNhcyIsImlzcyI6IkFQSSBWZW5kYXMiLCJleHAiOjE2NzYyMzAxMTN9.i4ZqGq2l2sv_IWb1NvJQ8c30ZNfIs8xojk6LWTbif7Q

###
post {{baseUrl}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "nome": "Fulano de Tal",
    "cpf": "71725437007"
}

###
get {{baseUrl}}/2
Authorization: Bearer {{token}}

###
delete {{baseUrl}}/1
Authorization: Bearer {{token}}

###
put {{baseUrl}}/2
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "nome": "Sicrano de Mal"
}

###
get {{baseUrl}}?nome=si
Authorization: Bearer {{token}}