@baseUrl = http://localhost:8080/api/clientes

###
post {{baseUrl}}
Content-Type: application/json

{
    "nome": "Fulano de Tal",
    "cpf": "11111111111"
}

###
get {{baseUrl}}/2

###
delete {{baseUrl}}/1

###
put {{baseUrl}}/2
Content-Type: application/json

{
    "nome": "Sicrano de Mal"
}

###
get {{baseUrl}}?nome=si