@baseUrl = http://localhost:8080/api/pedidos
@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJsdWNhcyIsImlzcyI6IkFQSSBWZW5kYXMiLCJleHAiOjE2NzU3MTgxODB9.O8ksTdTThOuSeqq0i5V95p8fEkkXE80g-xgNfrFf1mI

###
post {{baseUrl}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "cliente": 1,
    "total": 1500,
    "items": [
        {
            "produto": 1,
            "quantidade": 10
        }
    ]
}

###
get {{baseUrl}}/1
Authorization: Bearer {{token}}

###
patch {{baseUrl}}/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "novoStatus": "CANCELADO"
}