@baseUrl = http://localhost:8080/api/pedidos
@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJsdWNhcyIsImlzcyI6IkFQSSBWZW5kYXMiLCJleHAiOjE2NzYyMzAxMTN9.i4ZqGq2l2sv_IWb1NvJQ8c30ZNfIs8xojk6LWTbif7Q

###
post {{baseUrl}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "cliente": 1,
    "total": 1500,
    "items": [
        {
            "produto": 1,
            "quantidade": 10
        }
    ]
}

###
get {{baseUrl}}/1
Authorization: Bearer {{token}}

###
patch {{baseUrl}}/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "novoStatus": "CANCELADO"
}