@baseUrl = http://localhost:8080/api/usuarios

###
get {{baseUrl}}

###
post {{baseUrl}}
Content-Type: application/json

{
    "login": "lucas",
    "password": "123"
}

###
post {{baseUrl}}/auth
Content-Type: application/json

{
    "login": "lucas",
    "senha": "123"
}